name: "FRC West Curriculum"
description: "FRC West's Robotics Curriculum"

url: http://joelg236.github.io/frc-west-curriculum

markdown: rdiscount

# Site Navigation
courses:
-
    course: CSE 1110
    base: /courses/CSE 1110
    url: http://joelg236.github.io/frc-west-curriculum/courses/CSE%201110/home
    groups:
    -
        group: Programs
        units:
        -
            unit: Programming
            base: /courses/CSE 1110/1 - Programs/1 - Programming
            url: http://joelg236.github.io/frc-west-curriculum/courses/CSE%201110/1%20-%20Programs/1%20-%20Programming
        -
            unit: Languages
            base: /courses/CSE 1110/1 - Programs/2 - Languages
            url: http://joelg236.github.io/frc-west-curriculum/courses/CSE%201110/1%20-%20Programs/2%20-%20Languages
        -
            unit: Libraries
            base: /courses/CSE 1110/1 - Programs/3 - Libraries
            url: http://joelg236.github.io/frc-west-curriculum/courses/CSE%201110/1%20-%20Programs/3%20-%20Libraries
        -
            unit: Binary
            base: /courses/CSE 1110/1 - Programs/4 - Binary
            url: http://joelg236.github.io/frc-west-curriculum/courses/CSE%201110/1%20-%20Programs/4%20-%20Binary

    -
        group: Data
        units:
        -
            unit: Data Types
            base: /courses/CSE 1110/2 - Data/1 - Data Types
            url: http://joelg236.github.io/frc-west-curriculum/courses/CSE%201110/2%20-%20Data/1%20-%20Data%20Types
        -
            unit: Variables
            base: /courses/CSE 1110/2 - Data/2 - Variables
            url: http://joelg236.github.io/frc-west-curriculum/courses/CSE%201110/2%20-%20Data/2%20-%20Variables
        -
            unit: Input and Output
            base: /courses/CSE 1110/2 - Data/3 - Input and Output
            url: http://joelg236.github.io/frc-west-curriculum/courses/CSE%201110/2%20-%20Data/3%20-%20Input%20and%20Output

    -
        group: Basic Calculations
        units:
        -
            unit: Intro
            base: /courses/CSE 1110/3 - Basic Calculations/1 - Intro
            url: http://joelg236.github.io/frc-west-curriculum/courses/CSE%201110/3%20-%20Basic%20Calculations/1%20-%20Intro
        -
            unit: Activity
            base: /courses/CSE 1110/3 - Basic Calculations/2 - Activity
            url: http://joelg236.github.io/frc-west-curriculum/courses/CSE%201110/3%20-%20Basic%20Calculations/2%20-%20Activity

    -
        group: Algorithms
        units:
        -
            unit: Control Flow
            base: /courses/CSE 1110/4 - Algorithms/1 - Control Flow
            url: http://joelg236.github.io/frc-west-curriculum/courses/CSE%201110/4%20-%20Algorithms/1%20-%20Control%20Flow
        -
            unit: Functions
            base: /courses/CSE 1110/4 - Algorithms/2 - Functions
            url: http://joelg236.github.io/frc-west-curriculum/courses/CSE%201110/4%20-%20Algorithms/2%20-%20Functions
        -
            unit: Input and Output
            base: /courses/CSE 1110/4 - Algorithms/3 - Input and Output
            url: http://joelg236.github.io/frc-west-curriculum/courses/CSE%201110/4%20-%20Algorithms/3%20-%20Input%20and%20Output

    -
        group: Calculator
        units:
        -
            unit: Intro
            base: /courses/CSE 1110/5 - Calculator/1 - Intro
            url: http://joelg236.github.io/frc-west-curriculum/courses/CSE%201110/5%20-%20Calculator/1%20-%20Intro
        -
            unit: Activity
            base: /courses/CSE 1110/5 - Calculator/2 - Activity
            url: http://joelg236.github.io/frc-west-curriculum/courses/CSE%201110/5%20-%20Calculator/2%20-%20Activity

    -
        group: Environment
        units:
        -
            unit: Running Programs
            base: /courses/CSE 1110/6 - Environment/1 - Running Programs
            url: http://joelg236.github.io/frc-west-curriculum/courses/CSE%201110/6%20-%20Environment/1%20-%20Running%20Programs
        -
            unit: Programming Tools
            base: /courses/CSE 1110/6 - Environment/2 - Programming Tools
            url: http://joelg236.github.io/frc-west-curriculum/courses/CSE%201110/6%20-%20Environment/2%20-%20Programming%20Tools
        -
            unit: Debugging
            base: /courses/CSE 1110/6 - Environment/3 - Debugging
            url: http://joelg236.github.io/frc-west-curriculum/courses/CSE%201110/6%20-%20Environment/3%20-%20Debugging

    -
        group: FRC
        units:
        -
            unit: FRC Programming
            base: /courses/CSE 1110/7 - FRC/1 - FRC Programming
            url: http://joelg236.github.io/frc-west-curriculum/courses/CSE%201110/7%20-%20FRC/1%20-%20FRC%20Programming

    -
        group: Tests
        units:


-
    course: ELT 1010
    base: /courses/ELT 1010
    url: http://joelg236.github.io/frc-west-curriculum/courses/ELT%201010/home
    groups:
    -
        group: Safety
        units:
        -
            unit: Workplace Management
            base: /courses/ELT 1010/1 - Safety/1 - Workplace Management
            url: http://joelg236.github.io/frc-west-curriculum/courses/ELT%201010/1%20-%20Safety/1%20-%20Workplace%20Management
        -
            unit: Safe Work Practices
            base: /courses/ELT 1010/1 - Safety/2 - Safe Work Practices
            url: http://joelg236.github.io/frc-west-curriculum/courses/ELT%201010/1%20-%20Safety/2%20-%20Safe%20Work%20Practices
        -
            unit: Hazard Identification and Control
            base: /courses/ELT 1010/1 - Safety/3 - Hazard Identification and Control
            url: http://joelg236.github.io/frc-west-curriculum/courses/ELT%201010/1%20-%20Safety/3%20-%20Hazard%20Identification%20and%20Control

    -
        group: Electronics
        units:
        -
            unit: Curcuits
            base: /courses/ELT 1010/2 - Electronics/1 - Curcuits
            url: http://joelg236.github.io/frc-west-curriculum/courses/ELT%201010/2%20-%20Electronics/1%20-%20Curcuits
        -
            unit: Electrical Components
            base: /courses/ELT 1010/2 - Electronics/2 - Electrical Components
            url: http://joelg236.github.io/frc-west-curriculum/courses/ELT%201010/2%20-%20Electronics/2%20-%20Electrical%20Components
        -
            unit: Electronic Devices
            base: /courses/ELT 1010/2 - Electronics/3 - Electronic Devices
            url: http://joelg236.github.io/frc-west-curriculum/courses/ELT%201010/2%20-%20Electronics/3%20-%20Electronic%20Devices
        -
            unit: Electronic Connections
            base: /courses/ELT 1010/2 - Electronics/4 - Electronic Connections
            url: http://joelg236.github.io/frc-west-curriculum/courses/ELT%201010/2%20-%20Electronics/4%20-%20Electronic%20Connections

    -
        group: Fabrication of Components
        units:
        -
            unit: Soldering
            base: /courses/ELT 1010/3 - Fabrication of Components/1 - Soldering
            url: http://joelg236.github.io/frc-west-curriculum/courses/ELT%201010/3%20-%20Fabrication%20of%20Components/1%20-%20Soldering
        -
            unit: Application of Electronic Components
            base: /courses/ELT 1010/3 - Fabrication of Components/2 - Application of Electronic Components
            url: http://joelg236.github.io/frc-west-curriculum/courses/ELT%201010/3%20-%20Fabrication%20of%20Components/2%20-%20Application%20of%20Electronic%20Components
        -
            unit: Analog Connections
            base: /courses/ELT 1010/3 - Fabrication of Components/3 - Analog Connections
            url: http://joelg236.github.io/frc-west-curriculum/courses/ELT%201010/3%20-%20Fabrication%20of%20Components/3%20-%20Analog%20Connections
        -
            unit: Digital Connections
            base: /courses/ELT 1010/3 - Fabrication of Components/4 - Digital Connections
            url: http://joelg236.github.io/frc-west-curriculum/courses/ELT%201010/3%20-%20Fabrication%20of%20Components/4%20-%20Digital%20Connections

    -
        group: Tests
        units:
        -
            unit: Safety
            base: /courses/ELT 1010/Tests/1 - Safety
            url: http://joelg236.github.io/frc-west-curriculum/courses/ELT%201010/Tests/1%20-%20Safety
        -
            unit: Electronics
            base: /courses/ELT 1010/Tests/2 - Electronics
            url: http://joelg236.github.io/frc-west-curriculum/courses/ELT%201010/Tests/2%20-%20Electronics
        -
            unit: Fabrication of Components
            base: /courses/ELT 1010/Tests/3 - Fabrication of Components
            url: http://joelg236.github.io/frc-west-curriculum/courses/ELT%201010/Tests/3%20-%20Fabrication%20of%20Components


-
    course: ELT 1130
    base: /courses/ELT 1130
    url: http://joelg236.github.io/frc-west-curriculum/courses/ELT%201130/home
    groups:
    -
        group: Robots
        units:
        -
            unit: Principles
            base: /courses/ELT 1130/1 - Robots/1 - Principles
            url: http://joelg236.github.io/frc-west-curriculum/courses/ELT%201130/1%20-%20Robots/1%20-%20Principles
        -
            unit: Control
            base: /courses/ELT 1130/1 - Robots/2 - Control
            url: http://joelg236.github.io/frc-west-curriculum/courses/ELT%201130/1%20-%20Robots/2%20-%20Control
        -
            unit: Design
            base: /courses/ELT 1130/1 - Robots/3 - Design
            url: http://joelg236.github.io/frc-west-curriculum/courses/ELT%201130/1%20-%20Robots/3%20-%20Design
        -
            unit: Usage
            base: /courses/ELT 1130/1 - Robots/4 - Usage
            url: http://joelg236.github.io/frc-west-curriculum/courses/ELT%201130/1%20-%20Robots/4%20-%20Usage

    -
        group: Subsystems
        units:
        -
            unit: Motors
            base: /courses/ELT 1130/2 - Subsystems/1 - Motors
            url: http://joelg236.github.io/frc-west-curriculum/courses/ELT%201130/2%20-%20Subsystems/1%20-%20Motors
        -
            unit: Pneumatics
            base: /courses/ELT 1130/2 - Subsystems/2 - Pneumatics
            url: http://joelg236.github.io/frc-west-curriculum/courses/ELT%201130/2%20-%20Subsystems/2%20-%20Pneumatics
        -
            unit: Electronics
            base: /courses/ELT 1130/2 - Subsystems/3 - Electronics
            url: http://joelg236.github.io/frc-west-curriculum/courses/ELT%201130/2%20-%20Subsystems/3%20-%20Electronics
        -
            unit: Drivetrains
            base: /courses/ELT 1130/2 - Subsystems/4 - Drivetrains
            url: http://joelg236.github.io/frc-west-curriculum/courses/ELT%201130/2%20-%20Subsystems/4%20-%20Drivetrains

    -
        group: Power Sources
        units:
        -
            unit: Electricity
            base: /courses/ELT 1130/3 - Power Sources/1 - Electricity
            url: http://joelg236.github.io/frc-west-curriculum/courses/ELT%201130/3%20-%20Power%20Sources/1%20-%20Electricity
        -
            unit: Pneumatic & Hydraulic
            base: /courses/ELT 1130/3 - Power Sources/2 - Pneumatic & Hydraulic
            url: http://joelg236.github.io/frc-west-curriculum/courses/ELT%201130/3%20-%20Power%20Sources/2%20-%20Pneumatic%20&%20Hydraulic

    -
        group: Vex Robot
        units:
        -
            unit: Intro
            base: /courses/ELT 1130/4 - Vex Robot/1 - Intro
            url: http://joelg236.github.io/frc-west-curriculum/courses/ELT%201130/4%20-%20Vex%20Robot/1%20-%20Intro
        -
            unit: Activity
            base: /courses/ELT 1130/4 - Vex Robot/2 - Activity
            url: http://joelg236.github.io/frc-west-curriculum/courses/ELT%201130/4%20-%20Vex%20Robot/2%20-%20Activity

    -
        group: Tests
        units:


-
    course: ELT 1140
    base: /courses/ELT 1140
    url: http://joelg236.github.io/frc-west-curriculum/courses/ELT%201140/home
    groups:
    -
        group: Robots
        units:
        -
            unit: History
            base: /courses/ELT 1140/1 - Robots/1 - History
            url: http://joelg236.github.io/frc-west-curriculum/courses/ELT%201140/1%20-%20Robots/1%20-%20History
        -
            unit: Industry
            base: /courses/ELT 1140/1 - Robots/2 - Industry
            url: http://joelg236.github.io/frc-west-curriculum/courses/ELT%201140/1%20-%20Robots/2%20-%20Industry
        -
            unit: Power Sources
            base: /courses/ELT 1140/1 - Robots/3 - Power Sources
            url: http://joelg236.github.io/frc-west-curriculum/courses/ELT%201140/1%20-%20Robots/3%20-%20Power%20Sources

    -
        group: Programming
        units:
        -
            unit: Motor Control
            base: /courses/ELT 1140/2 - Programming/1 - Motor Control
            url: http://joelg236.github.io/frc-west-curriculum/courses/ELT%201140/2%20-%20Programming/1%20-%20Motor%20Control
        -
            unit: Downloading
            base: /courses/ELT 1140/2 - Programming/2 - Downloading
            url: http://joelg236.github.io/frc-west-curriculum/courses/ELT%201140/2%20-%20Programming/2%20-%20Downloading

    -
        group: Robotic System
        units:
        -
            unit: Intro
            base: /courses/ELT 1140/3 - Robotic System/1 - Intro
            url: http://joelg236.github.io/frc-west-curriculum/courses/ELT%201140/3%20-%20Robotic%20System/1%20-%20Intro
        -
            unit: Activity
            base: /courses/ELT 1140/3 - Robotic System/2 - Activity
            url: http://joelg236.github.io/frc-west-curriculum/courses/ELT%201140/3%20-%20Robotic%20System/2%20-%20Activity

    -
        group: Tests
        units:


-
    course: ELT 1910
    base: /courses/ELT 1910
    url: http://joelg236.github.io/frc-west-curriculum/courses/ELT%201910/home
    groups:
    -
        group: Project
        units:
        -
            unit: Introduction
            base: /courses/ELT 1910/1 - Project/1 - Introduction
            url: http://joelg236.github.io/frc-west-curriculum/courses/ELT%201910/1%20-%20Project/1%20-%20Introduction
        -
            unit: Project
            base: /courses/ELT 1910/1 - Project/2 - Project
            url: http://joelg236.github.io/frc-west-curriculum/courses/ELT%201910/1%20-%20Project/2%20-%20Project


-
    course: Special Projects
    base: /courses/Special Projects
    url: http://joelg236.github.io/frc-west-curriculum/courses/Special%20Projects/home
    groups:
    -
        group: Proposal
        units:
        -
            unit: Proposal
            base: /courses/Special Projects/1 - Proposal/1 - Proposal
            url: http://joelg236.github.io/frc-west-curriculum/courses/Special%20Projects/1%20-%20Proposal/1%20-%20Proposal

    -
        group: Tests
        units:
        -
            unit: Self-Evaluation
            base: /courses/Special Projects/Tests/1 - Self-Evaluation
            url: http://joelg236.github.io/frc-west-curriculum/courses/Special%20Projects/Tests/1%20-%20Self-Evaluation


# Site Navigation
